name = "kings-world-static-site"
compatibility_date = "2026-03-12"
workers_dev = false
preview_urls = true

[assets]
directory = "./dist"
not_found_handling = "404-page"

[observability]
enabled = true
